# Generated by Django 4.0.6 on 2022-09-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dongleplans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_price', models.TextField()),
                ('plan_data', models.TextField()),
                ('plan_validity', models.TextField()),
                ('plan_usage', models.IntegerField()),
            ],
        ),
    ]
