# Generated by Django 4.0.6 on 2022-09-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField(max_length=10)),
                ('email', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
