# Generated by Django 4.0.6 on 2022-09-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNo', models.TextField()),
                ('hashPhone', models.TextField()),
                ('register', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField(max_length=10)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersDetails',
            fields=[
                ('joined', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('userCat', models.CharField(max_length=1)),
            ],
        ),
    ]
