# Generated by Django 4.0.6 on 2022-09-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='userId',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
