# Generated by Django 4.0.6 on 2022-09-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNo', models.TextField()),
                ('register', models.BooleanField()),
            ],
        ),
    ]
