# Generated by Django 4.0.6 on 2022-09-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_phone_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pincode', models.TextField()),
                ('state', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
