# Generated by Django 4.0.6 on 2022-09-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isAdmin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
