# Generated by Django 4.0.6 on 2022-09-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='phoneNo',
            field=models.TextField(default=1234567890),
            preserve_default=False,
        ),
    ]
