# Generated by Django 4.0.6 on 2022-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='Name',
            field=models.TextField(default='admin'),
            preserve_default=False,
        ),
    ]
