# Generated by Django 4.0.6 on 2022-10-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.TextField()),
                ('Email', models.TextField()),
                ('a', models.CharField(max_length=1)),
                ('Query', models.TextField()),
            ],
        ),
    ]
